<?php
/**
 * 请在下面完成你的语言配置
 */

return array(
    '86' => array(
        "sc" => "中国",
        "code" => 86,
        "pinyin" => "ZHONGGUO",
        "en" => "China",
        "locale" => "CN",
        "tc" => "中國",
    ),
    '63' => array(
        "sc" => "菲律宾",
        "code" => 63,
        "pinyin" => "FEILVBIN",
        "en" => "Philippines",
        "locale" => "PH",
        "tc" => "菲律賓",
    ),
    '852' => array(
        "sc" => "香港",
        "code" => 852,
        "pinyin" => "XIANGGANG",
        "en" => "Hongkong",
        "locale" => "HK",
        "tc" => "香港",
    ),
    '886' => array(
        "sc" => "台湾",
        "code" => 886,
        "pinyin" => "TAIWAN",
        "en" => "Taiwan",
        "locale" => "TWN",
        "tc" => "台灣",
    ),
    '853' => array(
        "sc" => "澳门",
        "code" => 853,
        "pinyin" => "AOMEN",
        "en" => "Macao",
        "locale" => "MO",
        "tc" => "澳門",
    ),
    '966' => array(
        "sc" => "沙特阿拉伯",
        "code" => 966,
        "pinyin" => "SHATEALABO",
        "en" => "Saudi Arabia",
        "locale" => "SA",
        "tc" => "沙特阿拉伯",
    ),
    '971' => array(
        "sc" => "迪拜",
        "code" => 971,
        "pinyin" => "DIBAI",
        "en" => "Dubai",
        "locale" => "AE",
        "tc" => "迪拜",
    ),
    '64' => array(
        "sc" => "新西兰",
        "code" => 64,
        "pinyin" => "XINXILAN",
        "en" => "New Zealand",
        "locale" => "NZ",
        "tc" => "新西蘭",
    ),

    '998' => array(
        "sc" => "乌兹别克斯坦",
        "code" => 998,
        "en" => "Uzbekistan",
        "locale" => "UZ",
    ),
    '967' => array(
        "sc" => "也门",
        "code" => 967,
        "en" => "Yemen",
        "locale" => "YE",
    ),
    '374' => array(
        "sc" => "亚美尼亚",
        "code" => 374,
        "en" => "Armenia",
        "locale" => "AM",
    ),
    '972' => array(
        "sc" => "以色列",
        "code" => 972,
        "en" => "Israel",
        "locale" => "IL",
    ),
    '964' => array(
        "sc" => "伊拉克",
        "code" => 964,
        "en" => "Iraq",
        "locale" => "IQ",
    ),
    '98' => array(
        "sc" => "伊朗",
        "code" => 98,
        "en" => "Iran",
        "locale" => "IR",
    ),
    '974' => array(
        "sc" => "卡塔尔",
        "code" => 974,
        "en" => "Qatar",
        "locale" => "QA",
    ),
    '963' => array(
        "sc" => "叙利亚",
        "code" => 963,
        "en" => "Syria",
        "locale" => "SY",
    ),
    '996' => array(
        "sc" => "吉尔吉斯斯坦",
        "code" => 996,
        "en" => "Kyrgyzstan",
        "locale" => "KG",
    ),
    '76' => array(
        "sc" => "哈萨克斯坦",
        "code" => 76,
        "en" => "Kazakhstan",
        "locale" => "KZ",
    ),
    '993' => array(
        "sc" => "土库曼斯坦",
        "code" => 993,
        "en" => "Turkmenistan",
        "locale" => "TM",
    ),
    '992' => array(
        "sc" => "塔吉克斯坦",
        "code" => 992,
        "en" => "Tajikistan",
        "locale" => "TJ",
    ),
    '970' => array(
        "sc" => "巴勒斯坦",
        "code" => 970,
        "en" => "Palestine",
        "locale" => "BL",
    ),
    '92' => array(
        "sc" => "巴基斯坦",
        "code" => 92,
        "en" => "Pakistan",
        "locale" => "PK",
    ),
    '973' => array(
        "sc" => "巴林",
        "code" => 973,
        "en" => "Bahrain",
        "locale" => "BH",
    ),
    '965' => array(
        "sc" => "科威特",
        "code" => 965,
        "en" => "Kuwait",
        "locale" => "KW",
    ),
    '962' => array(
        "sc" => "约旦",
        "code" => 962,
        "en" => "Jordan",
        "locale" => "JO",
    ),
    '994' => array(
        "sc" => "阿塞拜疆",
        "code" => 994,
        "en" => "Azerbaijan",
        "locale" => "AZ",
    ),
    '93' => array(
        "sc" => "阿富汗",
        "code" => 93,
        "en" => "Afghanistan",
        "locale" => "AF",
    ),
    '968' => array(
        "sc" => "阿曼",
        "code" => 968,
        "en" => "Oman",
        "locale" => "OM",
    ),
    '961' => array(
        "sc" => "黎巴嫩",
        "code" => 961,
        "en" => "Lebanon",
        "locale" => "LB",
    ),
    '213' => array(
        "sc" => "阿尔及利亚",
        "code" => 213,
        "en" => "Algeria",
        "locale" => "DZ",
    ),
    '94' => array(
        "sc" => "斯里兰卡",
        "code" => 94,
        "en" => "Sri Lanka",
        "locale" => "LK",
    ),
);
